# Generated by Django 2.0.5 on 2018-05-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='projectName',
        ),
    ]
